### ISSUE TITLE
macOS .dmg meta-issue

### ISSUE THREAD

**Issue by zmughal** [orbital-transfer-example/perl-gtk3-starter-basic#8]
- [ ] Add codesigning. Without codesigning, the user has to manually open the bundle <https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac>.
- [ ] Allow running directly from the .dmg. This means that anything that needs to be written (e.g., the gdk-pixbuf loader cache) should be written to the user's `$HOME` directory and not into the bundle (which is read-only when run from a .dmg). A possible solution is to list this directory in the application configuration.
- [ ] Use GtkApplication to set the name of the application in the menu bar (instead of just "perl").
